In [1]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

In [185]:
tiktok = pd.read_csv("final_data.csv", low_memory=False)

I want to know what is the average length of a comments made on the videos in the data set
I want to know the which user commented the most on the videos and his average response greater than the original comment size.

In [4]:
tiktok

,comment_id,text,video_id,create_time,like_count,status,author.unique_id,author.nickname,author.is_private,author.language,author.signature,author.custom_verify,author.uid,author.sec_uid,author.avatar_thumb,author.region,author.ins_id,author.youtube_channel_title,author.youtube_channel_id,author.twitter_id
0,6816879848683438085,But are you giving him a Tesla? Because he des...,6816821384652557574,1587178528,161,1,lissettecalv,Lissette | Influencer Coach,False,en,How to BUILD & MONETIZE a digital biz with pur...,Verified account,133202372536832000,MS4wLjABAAAAbX7SywQS04x1ilOoKHrpTZqhQ6lD32nRC6...,https://p77-sign-sg.tiktokcdn.com/musically-ma...,US,lissettecalv,NaN,NaN,NaN
1,6816846992812015622,David was just hoping for some help üò¢,6816821384652557574,1587170875,1165,1,hellomyfriend0_o,Isaac micallef,True,en,In bed watching Tiktok video's üò¥,NaN,6744596691107824645,MS4wLjABAAAADslkcxnt1mqt2oQwQEK8d0ybBHPuCO-geV...,https://p77-sign-sg.tiktokcdn.com/musically-ma...,MT,NaN,NaN,NaN,NaN
2,6816942564911628294,We ain‚Äôt forgot that time he tricked us all in...,6816821384652557574,1587193131,249,1,briancarrion_,Briancarrion,False,en,Might make you cringe ü§∑üèΩ‚Äç‚ôÇÔ∏è\nüáªüá™,Verified account,2165547,MS4wLjABAAAAKH09hef-gLcTyrzYygfGHMazAhFaLMML7-...,https://p16-sign-sg.tiktokcdn.com/musically-ma...,US,brian.carrion_,NaN,NaN,NaN
3,6816824764519301125,get him a tesla,6816821384652557574,1587165700,4038,1,slumpgodkayy,kaykay the slumpgod,False,en,üëª:@ kaykayyishere\nfollow my instagramüíñ,NaN,6586423495932313605,MS4wLjABAAAAI1dyIIb3qlBf3LhqS3-OJITdYuc3OcWlsd...,https://p16-sign-sg.tiktokcdn.com/musically-ma...,US,kaylemraley,NaN,NaN,NaN
4,6816821633249001477,david ur so hung,6816821384652557574,1587164971,100,1,_4den,dad,False,en,x kinda fell off,NaN,6740418744587650054,MS4wLjABAAAAykXQ0pVI4w-y3kI1omvYzOH2xnJN0iP3lf...,https://p77-sign-sg.tiktokcdn.com/tos-maliva-a...,US,_4den,aden burgess,UCe3pSCjGls_hByctWn91rqw,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165105,6831297427954581509,Sup I‚Äôm early,6831297085137095942,1590535380,8,1,dylannn_44,Dylan,False,en,Idk why I‚Äôm one this app still,NaN,6791792671733138438,MS4wLjABAAAAmFpqJUMC3x-JSU-6rMppK2lo0woTjbA6zn...,https://p16-sign-va.tiktokcdn.com/tos-maliva-a...,US,NaN,NaN,NaN,NaN
165106,6831297361822711814,ÔøºÔøº,6831297085137095942,1590535364,8,1,bartaintnosimpson,Swervz,False,en,16 üáµüá±,NaN,6609698955666849798,MS4wLjABAAAA95jNX3KPhg-W6altflOh1HYrxeJIrAdaw_...,https://p16-sign-va.tiktokcdn.com/musically-ma...,GB,NaN,Swervz,UCyIJ9P3_FRuBNwQWTuhitsQ,NaN
165107,6831297275164868613,Ayeeee,6831297085137095942,1590535344,8,1,glock23likemike,CookieS,True,en,NaN,NaN,6722284375361356805,MS4wLjABAAAA65x9QjdnOWJXuZuDyRLUGCg8CICNET5ZYs...,https://p16-sign-va.tiktokcdn.com/tos-maliva-a...,US,NaN,NaN,NaN,NaN
165108,6842810518533652485,neta yo lo tuve pero no sabia jajaja üòÇ,6831297085137095942,1593215979,7,1,cristophercastell5,Cristopher Castellanos,False,es,NaN,NaN,6595585779418103813,MS4wLjABAAAA_ZjgBAsSdGxZ4NVWoV3iZTWelmkqFygkM-...,https://p16-sign-va.tiktokcdn.com/musically-ma...,US,NaN,NaN,NaN,NaN
165109,6840892206023950342,@daviddobrik I‚Äôm so sorry for the bother i kno...,6831297085137095942,1592769338,7,1,hammyyyyyyy.x,üå¥,False,en,venmo: @kiki-xxxx,NaN,6838797400569103366,MS4wLjABAAAAyWXHXgenGB6utXDz2snBw22s5Zn1bzlMgd...,https://p16-sign-va.tiktokcdn.com/musically-ma...,US,NaN,NaN,NaN,NaN

In [192]:
tiktok['comment_size'] = tiktok['text'].map(len)

In [193]:
tiktok['comment_size'].mean()

31.05030585670159

Wanted to see the average length of comments left by users. was able to determine it to be 31 characters.

In [13]:
tiktok['comment_size']

0          56
1          37
2          78
3          15
4          16
         ...
165105     13
165106      2
165107      6
165108     38
165109    148
Name: comment_size, Length: 165110, dtype: int64

In [17]:
comment_min = tiktok["comment_size"].min()
comment_min

1

In [20]:
comment_max = tiktok['comment_size'].max()
comment_max

150

In [25]:
comment_range = comment_max - comment_min
comment_range

149

In [26]:
comment_size = tiktok['comment_size']

In [28]:
sorted_size = comment_size.sort_values().reset_index(drop=True)

In [31]:
sorted_size.median()

26.0

In [32]:
sorted_size.mean()

31.05030585670159

In [45]:
tiktok.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 165110 entries, 0 to 165109
Data columns (total 21 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   comment_id                    165110 non-null  int64
 1   text                          165110 non-null  object
 2   video_id                      165110 non-null  int64
 3   create_time                   165110 non-null  int64
 4   like_count                    165110 non-null  int64
 5   status                        165110 non-null  int64
 6   author.unique_id              165110 non-null  object
 7   author.nickname               165110 non-null  object
 8   author.is_private             165110 non-null  bool
 9   author.language               165110 non-null  object
 10  author.signature              126232 non-null  object
 11  author.custom_verify          746 non-null     object
 12  author.uid                    165110 non-null  int64
 13  author.sec_uid                165110 non-null  object
 14  author.avatar_thumb           165110 non-null  object
 15  author.region                 164975 non-null  object
 16  author.ins_id                 50110 non-null   object
 17  author.youtube_channel_title  19476 non-null   object
 18  author.youtube_channel_id     19476 non-null   object
 19  author.twitter_id             98 non-null      float64
 20  comment_size                  165110 non-null  int64
dtypes: bool(1), float64(1), int64(7), object(12)
memory usage: 25.4+ MB

In [46]:
num_records = tiktok.shape[0]

In [74]:
author_data = tiktok[['author.unique_id']].copy()

In [75]:
counts = [1] * num_records

author_data['author_cnt'] = counts

In [76]:
author_count = pd.DataFrame(data=(author_data.groupby('author.unique_id', as_index=False).count()))

In [77]:
author_count

             author.unique_id  author_cnt
0     ....................999          20
1                   ......eli          16
2                 .....laur3n           1
3                .....loyalty          21
4        .....vibes...only..x           1
...                       ...         ...
6042                 zxp_vano          54
6043                   zylofc         132
6044                 zywcia.a         129
6045                    zyxn1          21
6046               zz.qxcv382           1

[6047 rows x 2 columns]

In [84]:
author_count.mode()

             author.unique_id  author_cnt
0     ....................999         1.0
1                   ......eli         NaN
2                 .....laur3n         NaN
3                .....loyalty         NaN
4        .....vibes...only..x         NaN
...                       ...         ...
6042                 zxp_vano         NaN
6043                   zylofc         NaN
6044                 zywcia.a         NaN
6045                    zyxn1         NaN
6046               zz.qxcv382         NaN

[6047 rows x 2 columns]

In [144]:
tiktok['author_nickname'].mode()

0    _
Name: author_nickname, dtype: object

In [146]:
tiktok['author_nickname'] = tiktok['author_nickname'].str.replace(' ','')

In [147]:
tiktok.rename(columns={'author.nickname':'author_nickname'}, inplace=True)

In [148]:
tiktok.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 165110 entries, 0 to 165109
Data columns (total 21 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   comment_id                    165110 non-null  int64
 1   text                          165110 non-null  object
 2   video_id                      165110 non-null  int64
 3   create_time                   165110 non-null  int64
 4   like_count                    165110 non-null  int64
 5   status                        165110 non-null  int64
 6   author.unique_id              165110 non-null  object
 7   author_nickname               165110 non-null  object
 8   author.is_private             165110 non-null  bool
 9   author.language               165110 non-null  object
 10  author.signature              126232 non-null  object
 11  author.custom_verify          746 non-null     object
 12  author.uid                    165110 non-null  int64
 13  author.sec_uid                165110 non-null  object
 14  author.avatar_thumb           165110 non-null  object
 15  author.region                 164975 non-null  object
 16  author.ins_id                 50110 non-null   object
 17  author.youtube_channel_title  19476 non-null   object
 18  author.youtube_channel_id     19476 non-null   object
 19  author.twitter_id             98 non-null      float64
 20  comment_size                  165110 non-null  int64
dtypes: bool(1), float64(1), int64(7), object(12)
memory usage: 25.4+ MB

In [183]:
author = pd.DataFrame(data=(tiktok.query('author_nickname == "NessaTorres"')))

In [186]:
author

,comment_id,text,video_id,create_time,like_count,status,author.unique_id,author_nickname,author.is_private,author.language,...,author.custom_verify,author.uid,author.sec_uid,author.avatar_thumb,author.region,author.ins_id,author.youtube_channel_title,author.youtube_channel_id,author.twitter_id,comment_size
31269,6879080332458115077,Attempt #1 until david notices me and I win a ...,6877998406359371014,1601660712,0,1,nessza30,NessaTorres,False,en,...,NaN,6826133516738544646,MS4wLjABAAAAY-puWmveJE_lQ9kDiPuLvCc7OC_eYZxNIR...,https://p77-sign-sg.tiktokcdn.com/tos-maliva-a...,US,NaN,NaN,NaN,NaN,79
31445,6879080537219301382,Attempt #5 until david notices me and I win a ...,6877998406359371014,1601660757,0,1,nessza30,NessaTorres,False,en,...,NaN,6826133516738544646,MS4wLjABAAAAY-puWmveJE_lQ9kDiPuLvCc7OC_eYZxNIR...,https://p16-sign-va.tiktokcdn.com/tos-maliva-a...,US,NaN,NaN,NaN,NaN,79
31447,6879080573814554630,Attempt #6 until david notices me and I win a ...,6877998406359371014,1601660766,0,1,nessza30,NessaTorres,False,en,...,NaN,6826133516738544646,MS4wLjABAAAAY-puWmveJE_lQ9kDiPuLvCc7OC_eYZxNIR...,https://p16-sign-va.tiktokcdn.com/tos-maliva-a...,US,NaN,NaN,NaN,NaN,79
31449,6879080456076771334,Attempt #4 until david notices me and I win a ...,6877998406359371014,1601660741,0,1,nessza30,NessaTorres,False,en,...,NaN,6826133516738544646,MS4wLjABAAAAY-puWmveJE_lQ9kDiPuLvCc7OC_eYZxNIR...,https://p16-sign-va.tiktokcdn.com/tos-maliva-a...,US,NaN,NaN,NaN,NaN,79
31450,6879080620069994501,Attempt #7 until david notices me and I win a ...,6877998406359371014,1601660779,0,1,nessza30,NessaTorres,False,en,...,NaN,6826133516738544646,MS4wLjABAAAAY-puWmveJE_lQ9kDiPuLvCc7OC_eYZxNIR...,https://p16-sign-va.tiktokcdn.com/tos-maliva-a...,US,NaN,NaN,NaN,NaN,79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62403,6879080416419004421,Attempt #3 until david notices me and I win a ...,6877998406359371014,1601660729,0,1,nessza30,NessaTorres,False,en,...,NaN,6826133516738544646,MS4wLjABAAAAY-puWmveJE_lQ9kDiPuLvCc7OC_eYZxNIR...,https://p77-sign-sg.tiktokcdn.com/tos-maliva-a...,US,NaN,NaN,NaN,NaN,79
62404,6879080387306356742,Attempt #2 until david notices me and I win a ...,6877998406359371014,1601660721,0,1,nessza30,NessaTorres,False,en,...,NaN,6826133516738544646,MS4wLjABAAAAY-puWmveJE_lQ9kDiPuLvCc7OC_eYZxNIR...,https://p77-sign-sg.tiktokcdn.com/tos-maliva-a...,US,NaN,NaN,NaN,NaN,79
62405,6879080620069994501,Attempt #7 until david notices me and I win a ...,6877998406359371014,1601660779,0,1,nessza30,NessaTorres,False,en,...,NaN,6826133516738544646,MS4wLjABAAAAY-puWmveJE_lQ9kDiPuLvCc7OC_eYZxNIR...,https://p77-sign-sg.tiktokcdn.com/tos-maliva-a...,US,NaN,NaN,NaN,NaN,79
62652,6879080332458115077,Attempt #1 until david notices me and I win a ...,6877998406359371014,1601660712,0,1,nessza30,NessaTorres,False,en,...,NaN,6826133516738544646,MS4wLjABAAAAY-puWmveJE_lQ9kDiPuLvCc7OC_eYZxNIR...,https://p16-sign-va.tiktokcdn.com/tos-maliva-a...,US,NaN,NaN,NaN,NaN,79
62670,6879080456076771334,Attempt #4 until david notices me and I win a ...,6877998406359371014,1601660741,0,1,nessza30,NessaTorres,False,en,...,NaN,6826133516738544646,MS4wLjABAAAAY-puWmveJE_lQ9kDiPuLvCc7OC_eYZxNIR...,https://p16-sign-va.tiktokcdn.com/tos-maliva-a...,US,NaN,NaN,NaN,NaN,79

In [189]:
a_length = author['text'].map(len)

In [190]:
a_length.mean()

79.0

I wanted to figure out who was leaving the most post on these tiktok videos and see if there average comment size was larger than the datas average and was able to conclude that comment size is larger than the entire data set