In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [25]:
draft = pd.read_excel('Draft.xlsx')

I want to know if the demand for a quarterback has gone up
I want to know if the demand for running backs have gone down

In [4]:
draft

,Unnamed: 0,Rnd,Pick,Tm,Player,Pos,Age,To,AP1,PB,...,Yds.1,TD.1,Rec,Yds.2,TD.2,Tkl,Int.1,Sk,College/Univ,Year
0,0,1,1,PIT,Terry Bradshaw,QB,22.0,1983.0,1,3,...,2257.0,32.0,0.0,1.0,0.0,NaN,NaN,NaN,Louisiana Tech,1970
1,1,1,2,GNB,Mike McCoy,DT,22.0,1980.0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,Notre Dame,1970
2,2,1,3,CLE,Mike Phipps,QB,22.0,1981.0,0,0,...,1278.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,Purdue,1970
3,3,1,4,BOS,Phil Olsen,DT,22.0,1976.0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Utah St.,1970
4,4,1,5,BUF,Al Cowlings,DE,23.0,1979.0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,USC,1970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14491,248,7,249,SFO,Prince Charles Iworah,CB,23.0,2016.0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,West. Kentucky,2016
14492,249,7,250,CLE,Scooby Wright,ILB,22.0,2016.0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Arizona,2016
14493,250,7,251,PHI,Joe Walker,ILB,23.0,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Oregon,2016
14494,251,7,252,CAR,Beau Sandland,TE,23.0,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Montana St.,2016
14495,252,7,253,TEN,Kalan Reed,CB,22.0,2016.0,0,0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,Southern Miss,2016

In [5]:
age = draft['Age']

In [6]:
age.mean()

22.54635823114084

In [7]:
draft.tail()

,Unnamed: 0,Rnd,Pick,Tm,Player,Pos,Age,To,AP1,PB,...,Yds.1,TD.1,Rec,Yds.2,TD.2,Tkl,Int.1,Sk,College/Univ,Year
14491,248,7,249,SFO,Prince Charles Iworah,CB,23.0,2016.0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,West. Kentucky,2016
14492,249,7,250,CLE,Scooby Wright,ILB,22.0,2016.0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Arizona,2016
14493,250,7,251,PHI,Joe Walker,ILB,23.0,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Oregon,2016
14494,251,7,252,CAR,Beau Sandland,TE,23.0,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Montana St.,2016
14495,252,7,253,TEN,Kalan Reed,CB,22.0,2016.0,0,0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,Southern Miss,2016

In [11]:
draft['Year'].unique()

array([1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980,
       1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991,
       1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
       2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013,
       2014, 2015, 2016])

In [12]:
draft.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14496 entries, 0 to 14495
Data columns (total 30 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    14496 non-null  int64
 1   Rnd           14496 non-null  int64
 2   Pick          14496 non-null  int64
 3   Tm            14496 non-null  object
 4   Player        14496 non-null  object
 5   Pos           14496 non-null  object
 6   Age           10764 non-null  float64
 7   To            10604 non-null  float64
 8   AP1           14496 non-null  int64
 9   PB            14496 non-null  int64
 10  St            14496 non-null  int64
 11  CarAV         10604 non-null  float64
 12  DrAV          9237 non-null   float64
 13  G             10571 non-null  float64
 14  Cmp           981 non-null    float64
 15  Att           981 non-null    float64
 16  Yds           981 non-null    float64
 17  TD            981 non-null    float64
 18  Int           981 non-null    float64
 19  Att.1         2660 non-null   float64
 20  Yds.1         2660 non-null   float64
 21  TD.1          2660 non-null   float64
 22  Rec           3260 non-null   float64
 23  Yds.2         3260 non-null   float64
 24  TD.2          3260 non-null   float64
 25  Tkl           3760 non-null   float64
 26  Int.1         2498 non-null   float64
 27  Sk            2741 non-null   float64
 28  College/Univ  14453 non-null  object
 29  Year          14496 non-null  int64
dtypes: float64(19), int64(7), object(4)
memory usage: 3.3+ MB

In [15]:
position = draft.groupby('Pos')

In [19]:
position.sum()

,Unnamed: 0,Rnd,Pick,Age,To,AP1,PB,St,CarAV,DrAV,...,Att.1,Yds.1,TD.1,Rec,Yds.2,TD.2,Tkl,Int.1,Sk,Year
Pos,,,,,,,,,,,,,,,,,,,,,
C,72154,2125,72563,6706.0,589111.0,33,136,971,7191.0,5150.0,...,7.0,-6.0,0.0,30.0,93.0,6.0,177.0,0.0,0.0,813461
CB,6817,226,6877,1200.0,110874.0,1,2,16,170.0,163.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1554.0,52.0,5.5,120931
DB,391225,12088,393676,41686.0,3672912.0,158,570,4320,32960.0,22624.0,...,188.0,974.0,11.0,510.0,7340.0,35.0,149581.0,14931.0,2583.0,4879074
DE,167239,5266,168409,20790.0,1813012.0,83,284,2384,19243.0,13805.0,...,37.0,71.0,1.0,140.0,1207.0,17.0,49568.0,466.0,16000.5,2330123
DL,871,27,875,92.0,8048.0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,8044
DT,145717,4383,146633,14698.0,1290489.0,62,190,1499,12279.0,8052.0,...,23.0,19.0,8.0,27.0,172.0,10.0,34660.0,212.0,5776.5,1824810
FB,12511,411,12595,1917.0,164390.0,3,16,171,587.0,430.0,...,9568.0,35220.0,258.0,6469.0,48873.0,269.0,745.0,0.0,0.0,167998
FS,1510,48,1521,219.0,18144.0,0,0,3,33.0,33.0,...,0.0,0.0,0.0,0.0,0.0,0.0,391.0,8.0,3.0,22171
G,156136,4741,157075,14740.0,1280343.0,71,241,1982,14627.0,9909.0,...,4.0,-10.0,1.0,46.0,147.0,7.0,270.0,0.0,1.0,1871865
ILB,2885,93,2906,427.0,36287.0,0,0,8,87.0,85.0,...,0.0,0.0,0.0,0.0,0.0,0.0,715.0,4.0,21.5,42325
K,37816,1037,37989,2476.0,217585.0,21,48,380,1500.0,726.0,...,15.0,16.0,0.0,3.0,30.0,0.0,245.0,0.0,0.0,343597
KR,819,21,822,0.0,0.0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5952
LB,301314,9341,303199,32561.0,2862436.0,147,476,3463,28511.0,21207.0,...,84.0,511.0,1.0,102.0,880.0,24.0,109978.0,3575.0,9342.1,3747728
LS,374,11,376,47.0,2016.0,0,0,0,2.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4031
NT,19244,646,19381,3102.0,270723.0,10,43,298,2389.0,1732.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1252.0,31.0,876.8,272149
OL,6782,215,6821,889.0,48343.0,0,2,18,132.0,126.0,...,0.0,0.0,0.0,1.0,-5.0,0.0,2.0,0.0,0.0,78512
OLB,5581,184,5625,942.0,74589.0,1,2,16,156.0,154.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1065.0,21.0,77.5,88681
P,30846,891,30999,2509.0,221481.0,24,51,395,1213.0,635.0,...,334.0,596.0,4.0,4.0,41.0,0.0,170.0,0.0,0.0,304135
QB,109609,3289,110290,11019.0,921481.0,36,250,1089,10610.0,6650.0,...,48041.0,187280.0,1848.0,315.0,2539.0,26.0,499.0,0.0,0.0,1355665
RB,280063,8379,281718,26570.0,2326685.0,93,387,1703,17934.0,13620.0,...,460480.0,1867902.0,12951.0,87030.0,727089.0,2921.0,2300.0,3.0,0.0,3286878
S,1275,41,1284,181.0,18144.0,0,0,0,12.0,12.0,...,0.0,0.0,0.0,0.0,0.0,0.0,124.0,2.0,1.0,18143
SS,1351,46,1363,268.0,24190.0,1,1,4,46.0,45.0,...,0.0,0.0,0.0,0.0,0.0,0.0,527.0,8.0,7.0,24185
T,161398,5045,162463,16716.0,1461237.0,82,274,2254,16907.0,12793.0,...,6.0,38.0,0.0,153.0,1019.0,39.0,451.0,0.0,0.0,2119623
TE,140400,4236,141220,14158.0,1229120.0,41,191,1291,5621.0,3946.0,...,979.0,3634.0,31.0,60150.0,682828.0,5139.0,1463.0,3.0,6.5,1632555
WB,597,14,599,46.0,3954.0,0,0,0,8.0,0.0,...,5.0,-22.0,0.0,30.0,392.0,2.0,0.0,0.0,0.0,3944
WR,289574,8720,291325,28730.0,2519140.0,92,415,2303,19700.0,14204.0,...,7597.0,44465.0,190.0,166792.0,2377583.0,14532.0,3889.0,21.0,0.0,3486048

In [21]:
draft.query('Pos == "QB"')

,Unnamed: 0,Rnd,Pick,Tm,Player,Pos,Age,To,AP1,PB,...,Yds.1,TD.1,Rec,Yds.2,TD.2,Tkl,Int.1,Sk,College/Univ,Year
0,0,1,1,PIT,Terry Bradshaw,QB,22.0,1983.0,1,3,...,2257.0,32.0,0.0,1.0,0.0,NaN,NaN,NaN,Louisiana Tech,1970
2,2,1,3,CLE,Mike Phipps,QB,22.0,1981.0,0,0,...,1278.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,Purdue,1970
29,29,2,30,BUF,Dennis Shaw,QB,23.0,1975.0,0,0,...,420.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,San Diego St.,1970
50,50,2,51,MIN,Bill Cappleman,QB,23.0,1973.0,0,0,...,-2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,Florida St.,1970
125,125,5,126,NOR,Steve Ramsey,QB,22.0,1976.0,0,0,...,108.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,North Texas,1970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14429,186,6,187,WAS,Nate Sudfeld,QB,22.0,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Indiana,2016
14433,190,6,191,DET,Jake Rudock,QB,23.0,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Michigan,2016
14443,200,6,201,JAX,Brandon Allen,QB,24.0,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Arkansas,2016
14449,206,6,207,SFO,Jeff Driskel,QB,23.0,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Louisiana Tech,2016
14465,222,7,223,MIA,Brandon Doughty,QB,24.0,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,West. Kentucky,2016

In [74]:
qb = pd.DataFrame(data=(draft.query('Pos == "QB"')))

In [81]:
num_draft = qb.shape[0]

counts = [1] * num_draft

qb['draft_cnt'] = counts

In [82]:
qb1 = pd.DataFrame(qb.groupby('Year').count())

In [83]:
qb1.reset_index(inplace =True)

In [85]:
qb1

,Year,Unnamed: 0,Rnd,Pick,Tm,Player,Pos,Age,To,AP1,...,Yds.1,TD.1,Rec,Yds.2,TD.2,Tkl,Int.1,Sk,College/Univ,draft_cnt
0,1970,14,14,14,14,14,14,7,7,14,...,7,7,1,1,1,0,0,0,14,14
1,1971,21,21,21,21,21,21,10,10,21,...,10,10,1,1,1,0,0,0,21,21
2,1972,19,19,19,19,19,19,7,7,19,...,7,7,0,0,0,0,0,0,19,19
3,1973,22,22,22,22,22,22,12,12,22,...,11,11,3,3,3,0,0,0,22,22
4,1974,20,20,20,20,20,20,11,11,20,...,11,11,1,1,1,0,0,0,20,20
5,1975,20,20,20,20,20,20,8,8,20,...,7,7,1,1,1,0,0,0,20,20
6,1976,26,26,26,26,26,26,9,9,26,...,9,9,1,1,1,0,0,0,25,26
7,1977,18,18,18,18,18,18,14,14,18,...,13,13,1,1,1,0,0,0,18,18
8,1978,14,14,14,14,14,14,10,10,14,...,9,9,2,2,2,0,0,0,14,14
9,1979,15,15,15,15,15,15,10,10,15,...,10,10,1,1,1,0,0,0,15,15
10,1980,17,17,17,17,17,17,11,11,17,...,10,10,3,3,3,0,0,0,17,17
11,1981,16,16,16,16,16,16,8,8,16,...,7,7,1,1,1,0,0,0,16,16
12,1982,15,15,15,15,15,15,9,9,15,...,8,8,2,2,2,0,0,0,15,15
13,1983,16,16,16,16,16,16,13,13,16,...,12,12,5,5,5,0,0,0,16,16
14,1984,15,15,15,15,15,15,13,13,15,...,13,13,2,2,2,0,0,0,15,15
15,1985,11,11,11,11,11,11,6,6,11,...,5,5,2,2,2,0,0,0,11,11
16,1986,16,16,16,16,16,16,13,13,16,...,13,13,1,1,1,0,0,0,16,16
17,1987,19,19,19,19,19,19,14,14,19,...,14,14,4,4,4,0,0,0,19,19
18,1988,13,13,13,13,13,13,5,5,13,...,5,5,2,2,2,0,0,0,12,13
19,1989,16,16,16,16,16,16,8,8,16,...,6,6,1,1,1,0,0,0,16,16
20,1990,20,20,20,20,20,20,11,11,20,...,11,11,1,1,1,0,0,0,20,20
21,1991,13,13,13,13,13,13,10,10,13,...,10,10,1,1,1,0,0,0,13,13
22,1992,21,21,21,21,21,21,13,13,21,...,11,11,4,4,4,0,0,0,21,21
23,1993,8,8,8,8,8,8,8,8,8,...,8,8,2,2,2,0,0,0,8,8
24,1994,9,9,9,9,9,9,9,9,9,...,7,7,2,2,2,3,0,0,9,9
25,1995,14,14,14,14,14,14,10,10,14,...,10,10,5,5,5,4,0,0,14,14
26,1996,8,8,8,8,8,8,4,4,8,...,4,4,0,0,0,1,0,0,7,8
27,1997,11,11,11,11,11,11,9,9,11,...,8,8,2,2,2,3,0,0,11,11
28,1998,8,8,8,8,8,8,7,7,8,...,7,7,2,2,2,3,0,0,8,8
29,1999,13,13,13,13,13,13,12,12,13,...,12,12,5,5,5,4,0,0,13,13
30,2000,12,12,12,12,12,12,10,10,12,...,10,10,3,3,3,7,0,0,12,12
31,2001,11,11,11,11,11,11,9,9,11,...,9,9,3,3,3,8,0,0,11,11
32,2002,15,15,15,15,15,15,11,11,15,...,10,10,4,4,4,6,0,0,15,15
33,2003,13,13,13,13,13,13,13,13,13,...,11,11,7,7,7,8,0,0,13,13
34,2004,17,17,17,17,17,17,13,13,17,...,11,11,3,3,3,8,0,0,17,17
35,2005,14,14,14,14,14,14,10,10,14,...,10,10,4,4,4,10,0,0,14,14
36,2006,13,13,13,13,13,13,11,11,13,...,11,11,3,3,3,6,0,0,13,13
37,2007,11,11,11,11,11,11,11,11,11,...,9,9,6,6,6,7,0,0,11,11
38,2008,13,13,13,13,13,13,12,8,13,...,8,8,3,3,3,5,0,0,13,13
39,2009,11,11,11,11,11,11,11,8,11,...,7,7,2,2,2,4,0,0,11,11
40,2010,13,13,13,13,13,13,13,10,13,...,6,6,3,3,3,4,0,0,13,13
41,2011,12,12,12,12,12,12,12,11,12,...,10,10,6,6,6,8,0,0,12,12
42,2012,11,11,11,11,11,11,11,11,11,...,9,9,5,5,5,5,0,0,11,11
43,2013,11,11,11,11,11,11,11,8,11,...,8,8,3,3,3,3,0,0,11,11
44,2014,14,14,14,14,14,14,14,10,14,...,9,9,3,3,3,3,0,0,14,14
45,2015,7,7,7,7,7,7,7,7,7,...,6,6,1,1,1,0,0,0,7,7
46,2016,15,15,15,15,15,15,15,9,15,...,8,8,1,1,1,0,0,0,15,15

In [112]:
qb1['Year'].cov(qb1['draft_cnt'])

-34.08695652173913

I wanted to see if the number of quarterbacks being drafted is increasing or decreasing over time. I found a negative corolation which means less quarterbacks are being drafted now than back in 1970.

In [36]:
qb1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 30 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Year          47 non-null     int64
 1   Unnamed: 0    47 non-null     int64
 2   Rnd           47 non-null     int64
 3   Pick          47 non-null     int64
 4   Tm            47 non-null     int64
 5   Player        47 non-null     int64
 6   Pos           47 non-null     int64
 7   Age           47 non-null     int64
 8   To            47 non-null     int64
 9   AP1           47 non-null     int64
 10  PB            47 non-null     int64
 11  St            47 non-null     int64
 12  CarAV         47 non-null     int64
 13  DrAV          47 non-null     int64
 14  G             47 non-null     int64
 15  Cmp           47 non-null     int64
 16  Att           47 non-null     int64
 17  Yds           47 non-null     int64
 18  TD            47 non-null     int64
 19  Int           47 non-null     int64
 20  Att.1         47 non-null     int64
 21  Yds.1         47 non-null     int64
 22  TD.1          47 non-null     int64
 23  Rec           47 non-null     int64
 24  Yds.2         47 non-null     int64
 25  TD.2          47 non-null     int64
 26  Tkl           47 non-null     int64
 27  Int.1         47 non-null     int64
 28  Sk            47 non-null     int64
 29  College/Univ  47 non-null     int64
dtypes: int64(30)
memory usage: 11.1 KB

In [117]:
qb2 = pd.DataFrame(data=(qb.query('Rnd == 1')))

In [118]:
qb2 = pd.DataFrame(data=(qb2.groupby('Year').sum()))

In [119]:
qb2.reset_index(inplace=True)

In [120]:
qb2

,Year,Unnamed: 0,Rnd,Pick,Age,To,AP1,PB,St,CarAV,...,Att.1,Yds.1,TD.1,Rec,Yds.2,TD.2,Tkl,Int.1,Sk,draft_cnt
0,1970,2,2,4,44.0,3964.0,1,3,18,146.0,...,698.0,3535.0,45.0,0.0,1.0,0.0,0.0,0.0,0.0,2
1,1971,3,3,6,67.0,5953.0,0,3,30,220.0,...,923.0,4219.0,40.0,1.0,-7.0,0.0,0.0,0.0,0.0,3
2,1972,23,2,25,44.0,3961.0,0,0,1,18.0,...,85.0,312.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,2
3,1973,1,1,2,22.0,1982.0,1,1,6,81.0,...,247.0,1429.0,14.0,0.0,0.0,0.0,0.0,0.0,0.0,1
4,1975,0,1,1,22.0,1986.0,0,2,10,70.0,...,178.0,239.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,1
5,1976,5,1,6,22.0,1985.0,0,0,7,62.0,...,259.0,932.0,14.0,1.0,1.0,0.0,0.0,0.0,0.0,1
6,1977,44,2,46,45.0,3970.0,0,1,7,72.0,...,230.0,550.0,8.0,1.0,23.0,1.0,0.0,0.0,0.0,2
7,1978,16,1,17,23.0,1989.0,0,0,6,56.0,...,220.0,884.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0,1
8,1979,30,3,33,68.0,5963.0,0,2,14,133.0,...,605.0,2422.0,23.0,2.0,7.0,0.0,0.0,0.0,0.0,3
9,1980,41,2,43,44.0,3979.0,0,0,10,62.0,...,300.0,1239.0,23.0,1.0,90.0,1.0,0.0,0.0,0.0,2
10,1981,5,1,6,22.0,1984.0,0,0,0,2.0,...,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
11,1982,7,2,9,45.0,3981.0,0,1,9,61.0,...,360.0,1792.0,17.0,5.0,72.0,2.0,0.0,0.0,0.0,2
12,1983,82,6,88,135.0,11965.0,4,25,53,506.0,...,1768.0,5765.0,57.0,7.0,122.0,1.0,0.0,0.0,0.0,6
13,1986,13,2,15,46.0,3988.0,0,1,11,98.0,...,291.0,684.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,2
14,1987,42,4,46,91.0,7998.0,0,4,31,229.0,...,1199.0,5337.0,35.0,5.0,-2.0,0.0,0.0,0.0,0.0,4
15,1989,0,1,1,22.0,2000.0,0,6,11,97.0,...,327.0,1016.0,9.0,2.0,-19.0,0.0,0.0,0.0,0.0,1
16,1990,6,2,8,44.0,3994.0,0,0,9,70.0,...,206.0,524.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,2
17,1991,38,2,40,45.0,3987.0,0,0,0,5.0,...,26.0,50.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
18,1992,29,2,31,44.0,4002.0,0,0,3,34.0,...,142.0,584.0,1.0,1.0,-6.0,0.0,0.0,0.0,0.0,2
19,1993,1,2,3,44.0,4009.0,0,4,17,135.0,...,627.0,1894.0,19.0,1.0,-9.0,0.0,0.0,0.0,0.0,2
20,1994,7,2,9,44.0,4004.0,0,1,8,57.0,...,315.0,1051.0,6.0,2.0,-6.0,0.0,7.0,0.0,0.0,2
21,1995,6,2,8,44.0,4018.0,0,5,21,181.0,...,1043.0,4276.0,47.0,3.0,-9.0,0.0,12.0,0.0,0.0,2
22,1997,25,1,26,25.0,1998.0,0,0,0,1.0,...,13.0,-10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
23,1998,1,2,3,44.0,4016.0,7,14,17,178.0,...,490.0,794.0,18.0,1.0,-2.0,0.0,9.0,0.0,0.0,2
24,1999,24,5,29,112.0,10025.0,0,9,21,231.0,...,1406.0,7524.0,69.0,9.0,-14.0,0.0,24.0,0.0,0.0,5
25,2000,17,1,18,24.0,2010.0,0,0,6,55.0,...,180.0,465.0,7.0,0.0,7.0,0.0,3.0,0.0,0.0,1
26,2001,0,1,1,21.0,2015.0,0,4,7,93.0,...,873.0,6109.0,36.0,2.0,1.0,0.0,9.0,0.0,0.0,1
27,2002,33,3,36,69.0,6027.0,0,0,12,88.0,...,494.0,1819.0,11.0,3.0,8.0,0.0,11.0,0.0,0.0,3
28,2003,45,4,49,91.0,8051.0,0,3,20,179.0,...,681.0,1555.0,24.0,2.0,-11.0,0.0,34.0,0.0,0.0,4
29,2004,34,4,38,90.0,8059.0,0,15,38,369.0,...,1115.0,2784.0,27.0,1.0,-20.0,0.0,22.0,0.0,0.0,4
30,2005,47,3,50,65.0,6046.0,2,8,23,252.0,...,1210.0,5826.0,44.0,4.0,-8.0,0.0,16.0,0.0,0.0,3
31,2006,21,3,24,69.0,6039.0,0,3,14,129.0,...,696.0,3198.0,23.0,0.0,0.0,0.0,16.0,0.0,0.0,3
32,2007,21,2,23,44.0,4021.0,0,0,4,8.0,...,84.0,360.0,2.0,1.0,18.0,0.0,4.0,0.0,0.0,2
33,2008,19,2,21,46.0,4032.0,1,4,18,192.0,...,620.0,1592.0,20.0,2.0,35.0,0.0,7.0,0.0,0.0,2
34,2009,20,3,23,64.0,6047.0,0,1,16,147.0,...,616.0,2246.0,31.0,2.0,-6.0,0.0,16.0,0.0,0.0,3
35,2010,24,2,26,45.0,4028.0,0,0,6,54.0,...,340.0,1328.0,14.0,1.0,5.0,0.0,2.0,0.0,0.0,2
36,2011,27,4,31,89.0,8060.0,1,3,13,133.0,...,1058.0,5398.0,63.0,3.0,2.0,0.0,14.0,0.0,0.0,4
37,2012,29,4,33,97.0,8063.0,0,4,12,158.0,...,838.0,4378.0,31.0,2.0,-4.0,0.0,13.0,0.0,0.0,4
38,2013,15,1,16,23.0,2016.0,0,0,1,10.0,...,94.0,324.0,4.0,0.0,0.0,0.0,2.0,0.0,0.0,1
39,2014,54,3,57,64.0,6046.0,0,1,5,55.0,...,303.0,1748.0,10.0,1.0,20.0,1.0,3.0,0.0,0.0,3
40,2015,1,2,3,42.0,4032.0,0,1,4,46.0,...,201.0,979.0,11.0,1.0,41.0,1.0,0.0,0.0,0.0,2
41,2016,26,3,29,66.0,6048.0,0,0,1,9.0,...,65.0,191.0,3.0,1.0,7.0,0.0,0.0,0.0,0.0,3

In [122]:
qb2['Year'].cov(qb2['Rnd'])

4.229965156794425

I wanted to see if the number of quarterbacks being drafted in the first round is increasing or decreasing over the years. was able to determine that quarterbacks are bing drafted in. the first round more often now than they used to be.

In [94]:
rb = pd.DataFrame(data=(draft.query('Pos == "RB"')))

In [88]:
rb

,Unnamed: 0,Rnd,Pick,Tm,Player,Pos,Age,To,AP1,PB,...,Yds.1,TD.1,Rec,Yds.2,TD.2,Tkl,Int.1,Sk,College/Univ,Year
7,7,1,8,STL,Larry Stegent,RB,22.0,1971.0,0,0,...,NaN,NaN,1.0,12.0,0.0,NaN,NaN,NaN,Texas A&M,1970
10,10,1,11,DEN,Bobby Anderson,RB,22.0,1975.0,0,0,...,1282.0,9.0,84.0,861.0,2.0,NaN,NaN,NaN,Colorado,1970
17,17,1,18,BAL,Norm Bulaich,RB,23.0,1979.0,0,1,...,3362.0,30.0,224.0,1766.0,11.0,NaN,NaN,NaN,TCU,1970
18,18,1,19,DET,Steve Owens,RB,22.0,1974.0,0,1,...,2451.0,20.0,99.0,861.0,2.0,NaN,NaN,NaN,Oklahoma,1970
22,22,1,23,DAL,Duane Thomas,RB,23.0,1974.0,0,0,...,2038.0,21.0,38.0,297.0,3.0,NaN,NaN,NaN,West Texas A&M,1970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14458,215,6,216,DAL,Darius Jackson,RB,22.0,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,East. Michigan,2016
14478,235,7,236,DET,Dwayne Washington,RB,22.0,2016.0,0,0,...,265.0,1.0,10.0,62.0,0.0,NaN,NaN,NaN,Washington,2016
14479,236,7,237,NOR,Daniel Lasco,RB,23.0,2016.0,0,0,...,32.0,0.0,2.0,11.0,0.0,NaN,NaN,NaN,California,2016
14484,241,7,242,WAS,Keith Marshall,RB,22.0,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Georgia,2016
14489,246,7,247,SEA,Zac Brooks,RB,23.0,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Clemson,2016

In [95]:
rb1 = pd.DataFrame(data=(rb.groupby('Year').count()))

In [96]:
rb1.reset_index(inplace=True)

In [97]:
rb1

,Year,Unnamed: 0,Rnd,Pick,Tm,Player,Pos,Age,To,AP1,...,Att.1,Yds.1,TD.1,Rec,Yds.2,TD.2,Tkl,Int.1,Sk,College/Univ
0,1970,63,63,63,63,63,63,33,33,63,...,29,29,29,25,25,25,0,0,0,63
1,1971,62,62,62,62,62,62,32,32,62,...,32,32,32,29,29,29,0,0,0,62
2,1972,59,59,59,59,59,59,28,28,59,...,26,26,26,25,25,25,0,0,0,58
3,1973,61,61,61,61,61,61,24,24,61,...,23,23,23,23,23,23,0,0,0,61
4,1974,76,76,76,76,76,76,41,41,76,...,38,38,38,35,35,35,0,0,0,76
5,1975,73,73,73,73,73,73,33,33,73,...,31,31,31,31,31,31,0,1,0,71
6,1976,67,67,67,67,67,67,37,37,67,...,36,36,36,34,34,34,0,0,0,67
7,1977,48,48,48,48,48,48,36,36,48,...,33,33,33,31,31,31,0,0,0,48
8,1978,43,43,43,43,43,43,25,25,43,...,23,23,23,21,21,21,0,0,0,43
9,1979,46,46,46,46,46,46,37,37,46,...,35,35,35,35,35,35,0,1,0,46
10,1980,46,46,46,46,46,46,26,26,46,...,24,24,24,22,22,22,0,0,0,46
11,1981,45,45,45,45,45,45,30,30,45,...,28,28,28,28,28,28,0,0,0,45
12,1982,43,43,43,43,43,43,35,35,43,...,31,31,31,27,27,27,0,0,0,43
13,1983,45,45,45,45,45,45,27,27,45,...,25,25,25,22,22,22,0,0,0,45
14,1984,48,48,48,48,48,48,35,35,48,...,32,32,32,26,26,26,0,0,0,48
15,1985,33,33,33,33,33,33,26,26,33,...,24,24,24,24,24,24,0,0,0,33
16,1986,47,47,47,47,47,47,38,38,47,...,35,35,35,34,34,34,0,0,0,47
17,1987,55,55,55,55,55,55,47,47,55,...,43,43,43,39,39,39,0,0,0,55
18,1988,40,40,40,40,40,40,27,27,40,...,25,25,25,23,23,23,0,1,0,40
19,1989,46,46,46,46,46,46,34,34,46,...,30,30,30,29,29,29,0,0,0,46
20,1990,39,39,39,39,39,39,25,25,39,...,24,24,24,23,23,23,0,0,0,39
21,1991,39,39,39,39,39,39,28,28,39,...,26,26,26,26,26,26,0,0,0,39
22,1992,28,28,28,28,28,28,18,18,28,...,16,16,16,16,16,16,0,0,0,28
23,1993,19,19,19,19,19,19,17,17,19,...,16,16,16,16,16,16,0,0,0,19
24,1994,26,26,26,26,26,26,21,21,26,...,17,17,17,17,17,17,6,0,0,26
25,1995,21,21,21,21,21,21,20,20,21,...,20,20,20,19,19,19,6,0,0,21
26,1996,30,30,30,30,30,30,26,26,30,...,24,24,24,24,24,24,8,0,0,30
27,1997,19,19,19,19,19,19,16,16,19,...,15,15,15,16,16,16,7,0,0,19
28,1998,25,25,25,25,25,25,19,19,25,...,18,18,18,17,17,17,6,0,0,25
29,1999,18,18,18,18,18,18,17,17,18,...,15,15,15,17,17,17,11,0,0,18
30,2000,20,20,20,20,20,20,19,19,20,...,19,19,19,18,18,18,16,0,0,20
31,2001,16,16,16,16,16,16,15,15,16,...,14,14,14,14,14,14,15,0,0,16
32,2002,23,23,23,23,23,23,20,20,23,...,17,17,17,19,19,19,16,0,0,23
33,2003,15,15,15,15,15,15,11,11,15,...,11,11,11,11,11,11,11,0,0,15
34,2004,16,16,16,16,16,16,16,16,16,...,14,14,14,14,14,14,14,0,0,16
35,2005,22,22,22,22,22,22,18,18,22,...,16,16,16,16,16,16,14,0,0,22
36,2006,17,17,17,17,17,17,16,16,17,...,12,12,12,12,12,12,13,0,0,17
37,2007,22,22,22,22,22,22,18,18,22,...,18,18,18,18,18,18,18,0,0,22
38,2008,23,23,23,23,23,23,23,21,23,...,19,19,19,19,19,19,16,0,0,23
39,2009,23,23,23,23,23,23,23,22,23,...,22,22,22,22,22,22,17,0,0,23
40,2010,15,15,15,15,15,15,13,13,15,...,12,12,12,13,13,13,10,0,0,15
41,2011,29,29,29,29,29,29,29,27,29,...,26,26,26,26,26,26,24,0,0,29
42,2012,21,21,21,21,21,21,21,21,21,...,18,18,18,19,19,19,13,0,0,21
43,2013,25,25,25,25,25,25,25,23,25,...,23,23,23,23,23,23,16,0,0,25
44,2014,19,19,19,19,19,19,19,17,19,...,16,16,16,16,16,16,10,0,0,19
45,2015,18,18,18,18,18,18,18,17,18,...,17,17,17,17,17,17,0,0,0,18
46,2016,20,20,20,20,20,20,20,15,20,...,15,15,15,15,15,15,1,0,0,20

In [123]:
rb1['Year'].cov(rb1['Pick'])

-207.47826086956516

wanted to see the trend for rb being drafted year over year. by using covarience was able to conclude that rb are being drafted less often

In [107]:
rb2 = pd.DataFrame(data=(rb.query('Rnd == 1')))

In [108]:
rb2 = pd.DataFrame(data=(rb2.groupby('Year').count()))

In [109]:
rb2.reset_index(inplace=True)

In [110]:
rb2

,Year,Unnamed: 0,Rnd,Pick,Tm,Player,Pos,Age,To,AP1,...,Att.1,Yds.1,TD.1,Rec,Yds.2,TD.2,Tkl,Int.1,Sk,College/Univ
0,1970,5,5,5,5,5,5,5,5,5,...,4,4,4,5,5,5,0,0,0,5
1,1971,8,8,8,8,8,8,8,8,8,...,8,8,8,8,8,8,0,0,0,8
2,1972,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,0,0,0,3
3,1973,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,0,0,0,4
4,1974,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,0,0,0,6
5,1975,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,0,0,0,2
6,1976,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,0,0,0,6
7,1977,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,0,0,0,2
8,1978,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,0,0,0,3
9,1979,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,0,0,0,5
10,1980,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,0,0,0,5
11,1981,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,0,0,0,6
12,1982,7,7,7,7,7,7,7,7,7,...,7,7,7,7,7,7,0,0,0,7
13,1983,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,0,0,0,4
14,1984,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,0,0,0,1
15,1985,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,0,0,0,3
16,1986,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,0,0,0,5
17,1987,7,7,7,7,7,7,7,7,7,...,7,7,7,7,7,7,0,0,0,7
18,1988,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,0,0,0,5
19,1989,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,0,0,0,5
20,1990,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,0,0,0,6
21,1991,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,0,0,0,2
22,1992,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,0,0,0,3
23,1993,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,0,0,0,3
24,1994,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,1,0,0,2
25,1995,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,2,0,0,5
26,1996,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,2,0,0,3
27,1997,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,0,0,2
28,1998,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,2,0,0,4
29,1999,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,0,0,2
30,2000,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,0,0,5
31,2001,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,0,0,3
32,2002,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,0,0,2
33,2003,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,0,0,2
34,2004,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,0,0,3
35,2005,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,0,0,3
36,2006,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,0,0,4
37,2007,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,0,0,2
38,2008,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,0,0,5
39,2009,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,0,0,3
40,2010,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,0,0,3
41,2011,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,0,0,1
42,2012,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,0,0,3
43,2015,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,0,0,0,2
44,2016,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,0,0,0,1

In [111]:
rb2['Year'].cov(rb2['Pick'])

-11.1989898989899

wanted to see if, like quarterbacks , are being drafted less but more in the first round and was able to see using covarience that they are being drafted in the first round less often.

Questions to be answered: 

1. Where are RB being drafted most frequently
2. What is the average round QB are drafted in per year